title: Your awesome title
author: bit0byte8
email: test@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the long description
  this is short description

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
